version: 2.1
jobs:
  guardian-of-style:
    docker:
      - image: cimg/node:20.8.1
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run ESLint
          command: npx eslint . --format junit -o test-results/lint-results.xml
      - store_artifacts:
          path: test-results/
          destination: lint-style-results
      - store_test_results:
          path: test-results/
  smoke-test-gate:
    docker:
      - image: cimg/node:20.8.1
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run Smoke Tests
          command: npm run smoke-test
workflows:
  version: 2
  sanctuary-check:
    jobs:
      - smoke-test-gate:
          filters:
            branches:
              only: main
      - guardian-of-style