version: 2.1

jobs:
  vessel-builder:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image with BuildKit
          command: docker build -t donbaris/sanctuary:latest .
      - run:
          name: Authenticate and Push to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push donbaris/sanctuary:latest

workflows:
  version: 2
  sanctuary-check:
    jobs:
      - vessel-builder:
          filters:
            branches:
              only:
                - main
                - release/*